# Generated by Django 3.2 on 2021-12-14 18:49

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(default='work/default.jpeg', upload_to=work.models.upload_to, verbose_name='Image'),
        ),
    ]
