# Generated by Django 3.2 on 2021-12-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_built'),
    ]

    operations = [
        migrations.RenameField(
            model_name='built',
            old_name='backend_framework',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='built',
            old_name='frontend_framework',
            new_name='frontend',
        ),
    ]
