# Generated by Django 3.2 on 2021-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
